modLoader="javafml" #m
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/MalTeeez/modname/issues"

[[mods]] #m
modId="inador" #m
version="${file.jarVersion}" #m
displayName="InAdor" #m
displayURL="http://91.200.100.15/"
logoFile="logo.png"
credits="<3"
authors="Bella, Mika"
description='''
Love, Cheese and small house plants

luv u bella. <3
'''
[[dependencies.inador]]
    modId="forge" #m
    mandatory=true #m
    versionRange="[32,)" #m
    ordering="NONE"
    side="BOTH"

[[dependencies.inador]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
